name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  set_project_list:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set_outputs.outputs.projects }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find lambda projects
        id: set_outputs
        run: |
          projects=$(find . -maxdepth 1 -type d -name 'lambda-*' | sed 's|./||' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "Found projects: $projects"
          echo "::set-output name=projects::$projects"

  npm_install:
    runs-on: ubuntu-latest
    needs: set_project_list
    strategy:
      matrix:
        project: ${{ fromJson(needs.set_project_list.outputs.projects) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          cd ${{ matrix.project }}
          npm install

  unit_test:
    runs-on: ubuntu-latest
    needs: npm_install
    strategy:
      matrix:
        project: ${{ fromJson(needs.set_project_list.outputs.projects) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Run unit tests
        run: |
          cd ${{ matrix.project }}
          npm test
